// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message/message.proto

package mimo_srv_message

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SrcId                string   `protobuf:"bytes,2,opt,name=srcId,proto3" json:"srcId,omitempty"`
	DstId                string   `protobuf:"bytes,3,opt,name=dstId,proto3" json:"dstId,omitempty"`
	MsgType              string   `protobuf:"bytes,4,opt,name=msgType,proto3" json:"msgType,omitempty"`
	Content              string   `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	ResType              string   `protobuf:"bytes,6,opt,name=resType,proto3" json:"resType,omitempty"`
	ResUrl               string   `protobuf:"bytes,7,opt,name=resUrl,proto3" json:"resUrl,omitempty"`
	CreateTime           int64    `protobuf:"varint,8,opt,name=createTime,proto3" json:"createTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebceca9e8703e37f, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Request) GetSrcId() string {
	if m != nil {
		return m.SrcId
	}
	return ""
}

func (m *Request) GetDstId() string {
	if m != nil {
		return m.DstId
	}
	return ""
}

func (m *Request) GetMsgType() string {
	if m != nil {
		return m.MsgType
	}
	return ""
}

func (m *Request) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Request) GetResType() string {
	if m != nil {
		return m.ResType
	}
	return ""
}

func (m *Request) GetResUrl() string {
	if m != nil {
		return m.ResUrl
	}
	return ""
}

func (m *Request) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

type Response struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebceca9e8703e37f, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "mimo.srv.message.Request")
	proto.RegisterType((*Response)(nil), "mimo.srv.message.Response")
}

func init() {
	proto.RegisterFile("message/message.proto", fileDescriptor_ebceca9e8703e37f)
}

var fileDescriptor_ebceca9e8703e37f = []byte{
	// 242 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xd1, 0x4a, 0xc3, 0x30,
	0x14, 0x86, 0x6d, 0xb7, 0xb5, 0xf3, 0x08, 0x22, 0x41, 0x25, 0xee, 0x42, 0x46, 0xaf, 0x76, 0x15,
	0x41, 0x1f, 0xc0, 0xeb, 0x5d, 0xe8, 0x45, 0x9d, 0x0f, 0x50, 0x9b, 0xc3, 0x28, 0x98, 0xa6, 0xe6,
	0x9c, 0x09, 0x3e, 0xa3, 0x2f, 0x25, 0x49, 0x8e, 0x20, 0xb2, 0xab, 0xf2, 0x7d, 0x1f, 0x4d, 0xc8,
	0x0f, 0x57, 0x0e, 0x89, 0xba, 0x3d, 0xde, 0xc9, 0xd7, 0x4c, 0xc1, 0xb3, 0x57, 0x17, 0x6e, 0x70,
	0xde, 0x50, 0xf8, 0x34, 0xe2, 0x9b, 0xef, 0x02, 0xea, 0x16, 0x3f, 0x0e, 0x48, 0xac, 0xce, 0xa1,
	0x1c, 0xac, 0x2e, 0xd6, 0xc5, 0xe6, 0xb4, 0x2d, 0x07, 0xab, 0x2e, 0x61, 0x41, 0xa1, 0xdf, 0x5a,
	0x5d, 0x26, 0x95, 0x21, 0x5a, 0x4b, 0xbc, 0xb5, 0x7a, 0x96, 0x6d, 0x02, 0xa5, 0xa1, 0x76, 0xb4,
	0xdf, 0x7d, 0x4d, 0xa8, 0xe7, 0xc9, 0xff, 0x62, 0x2c, 0xbd, 0x1f, 0x19, 0x47, 0xd6, 0x8b, 0x5c,
	0x04, 0x63, 0x09, 0x48, 0xe9, 0x9f, 0x2a, 0x17, 0x41, 0x75, 0x0d, 0x55, 0x40, 0x7a, 0x0d, 0xef,
	0xba, 0x4e, 0x41, 0x48, 0xdd, 0x02, 0xf4, 0x01, 0x3b, 0xc6, 0xdd, 0xe0, 0x50, 0x2f, 0xd7, 0xc5,
	0x66, 0xd6, 0xfe, 0x31, 0x4d, 0x03, 0xcb, 0x16, 0x69, 0xf2, 0x23, 0xa5, 0x33, 0x88, 0x3b, 0x3e,
	0x90, 0xbc, 0x48, 0xe8, 0xfe, 0x19, 0xce, 0x5e, 0x70, 0xb4, 0x4f, 0x79, 0x00, 0xf5, 0x08, 0xf3,
	0x88, 0xea, 0xc6, 0xfc, 0xdf, 0xc6, 0xc8, 0x2e, 0xab, 0xd5, 0xb1, 0x94, 0x6f, 0x69, 0x4e, 0xde,
	0xaa, 0x34, 0xed, 0xc3, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x86, 0x5d, 0x9f, 0xed, 0x73, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SendMessageClient is the client API for SendMessage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SendMessageClient interface {
	Send(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type sendMessageClient struct {
	cc grpc.ClientConnInterface
}

func NewSendMessageClient(cc grpc.ClientConnInterface) SendMessageClient {
	return &sendMessageClient{cc}
}

func (c *sendMessageClient) Send(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/mimo.srv.message.SendMessage/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SendMessageServer is the server API for SendMessage service.
type SendMessageServer interface {
	Send(context.Context, *Request) (*Response, error)
}

// UnimplementedSendMessageServer can be embedded to have forward compatible implementations.
type UnimplementedSendMessageServer struct {
}

func (*UnimplementedSendMessageServer) Send(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}

func RegisterSendMessageServer(s *grpc.Server, srv SendMessageServer) {
	s.RegisterService(&_SendMessage_serviceDesc, srv)
}

func _SendMessage_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SendMessageServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mimo.srv.message.SendMessage/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SendMessageServer).Send(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _SendMessage_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mimo.srv.message.SendMessage",
	HandlerType: (*SendMessageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _SendMessage_Send_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message/message.proto",
}
